// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rrywqexdnpueakimsvsi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJyeXdxZXhkbnB1ZWFraW1zdnNpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM3NDg2NzMsImV4cCI6MjA2OTMyNDY3M30.8mD2QyZOI7Fe3x3CUaSQ9cy75Uypa3HEKDGM8Jgdk7I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});